import type { Metadata } from "next";
import { Great_Vibes, Spectral } from "next/font/google";

import "./globals.css";
import { NavBar } from "@/components/nav/NavBar";
import Footer from "@/components/footer/Footer";
const geatVibes = Great_Vibes({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font--great-vibes",
});

const spectral = Spectral({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-spectral",
});


export const metadata: Metadata = {
  title: "Rincon del Aromo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geatVibes.variable} ${spectral.variable} font-sans antialiased`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
